version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./database:/app/database
      - ./api/.env:/app/api/.env
    restart: unless-stopped 